project:
  type: website
  output-dir: docs

website:
  title: "SPL Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: jfm.qmd
        text: Johnny Marr
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: globe2
        href: https://orcid.org/0000-0002-1893-4325

format:
  html:
    theme: lux
    css: styles.css
    toc: true



